import './tracker.css';
import './map-v2.css';
import { collection, doc, getDoc, getDocs, query, where } from 'firebase/firestore';
import { studentDb, isStudentConfigured } from '../firebase/studentFirebase.js';
import { mapStops } from '../data/mapStops.js';
import { getCrystalsToNextStop, getNextMapStop } from '../shared/calculations.js';
import { escapeHtml } from '../shared/formatters.js';
import { MAX_HOMEWORK_ICONS } from '../shared/constants.js';
import { renderMap } from './map.js';
const app=document.querySelector('#app');
const demoProfile={displayName:'Маша',balance:14,totalEarned:29,active:true,latestHomeworkCompleted:3,latestHomeworkTotal:5};
const demoRewards=[{id:'gift',title:'Таинственный подарок',cost:20,emoji:'🎁',active:true},{id:'game',title:'Игра на уроке',cost:10,emoji:'🎲',active:true},{id:'choice',title:'Выбрать домашку',cost:15,emoji:'✨',active:true}];
const notFound=()=>{app.innerHTML='<section class="state-screen"><div class="state-symbol">✨</div><h1>Эта волшебная карта не найдена</h1><p>Проверь ссылку или попроси преподавателя прислать новую.</p></section>';};
function homework(profile){const done=profile.latestHomeworkCompleted,total=profile.latestHomeworkTotal;if(!Number.isInteger(total))return '<p class="empty">Пока нет домашнего задания</p>';if(total<=MAX_HOMEWORK_ICONS)return `<div class="crystal-row" aria-hidden="true">${Array.from({length:total},(_,i)=>i<done?'💎':'◇').join(' ')}</div><strong>${done} / ${total}</strong>`;return `<strong class="large-ratio">${done} / ${total}</strong>`;}
function render(profile,rewards){const next=getNextMapStop(profile.totalEarned,mapStops); const remaining=getCrystalsToNextStop(profile.totalEarned,mapStops); app.innerHTML=`<div class="sky"><span></span><span></span><span></span></div><header class="hero"><p class="eyebrow">MAGIC PROGRESS</p><h1>Привет, ${escapeHtml(profile.displayName)}!</h1><div class="balance"><span>💎</span>${profile.balance}</div><p>Твои кристаллы</p></header><section class="map-card"><div class="section-heading"><div><p class="eyebrow">ТВОЁ ПУТЕШЕСТВИЕ</p><h2>Волшебная карта</h2></div><p class="next-stop">${next?`До «${escapeHtml(next.label)}» ещё <b>${remaining} 💎</b>`:'Ты открыл всю карту! ✨'}</p></div>${renderMap(profile.totalEarned,mapStops)}</section><div class="info-grid"><section class="glass homework"><p class="eyebrow">ПОСЛЕДНЕЕ ДЗ</p>${homework(profile)}</section><section class="glass journey"><p class="eyebrow">ВСЕГО В ПУТИ</p><strong>${profile.totalEarned} 💎</strong><span>заработано за всё время</span></section></div><section class="rewards"><p class="eyebrow">СОКРОВИЩА</p><h2>Награды</h2><div class="reward-grid">${rewards.length?rewards.map(r=>`<article><span>${escapeHtml(r.emoji||'🎁')}</span><h3>${escapeHtml(r.title)}</h3><b>${r.cost} 💎</b><p class="${profile.balance>=r.cost?'available':''}">${profile.balance>=r.cost?'Можно получить':`Ещё ${r.cost-profile.balance} 💎`}</p></article>`).join(''):'<p class="empty">Скоро здесь появятся награды</p>'}</div></section><footer>Продолжай своё волшебное путешествие ✦</footer>`;}
async function init(){const params=new URLSearchParams(location.search);const token=params.get('s');if(params.has('demo')||(!token&&!isStudentConfigured)){render(demoProfile,demoRewards);return;}if(!token)return notFound();if(!isStudentConfigured){app.innerHTML='<section class="state-screen"><div class="state-symbol">⚙️</div><h1>Firebase пока не настроен</h1><p>Для просмотра примера добавь к адресу ?demo=1.</p></section>';return;}try{const snap=await getDoc(doc(studentDb,'publicProfiles',token));if(!snap.exists()||snap.data().active!==true)return notFound();const rewardSnap=await getDocs(query(collection(studentDb,'rewards'),where('active','==',true)));render(snap.data(),rewardSnap.docs.map(x=>({id:x.id,...x.data()})));}catch(error){console.error(error);notFound();}} init();
